# 职责: random 模块的 MT19937 对齐 (D1): int 种子的 init_by_array 路径 / random / randint / randrange / choice / shuffle / sample / uniform / gauss / getrandbits / getstate / setstate 与 CPython 序列逐值一致, 无参种子用引擎随机源, 字符串种子序列与 CPython 不对齐 (sha512 差异文档化)
# 比对: same_output
# 锚定: CPython 3.12
import random

random.seed(42)
print("float:", [round(random.random(), 15) for _ in range(3)])
random.seed(42)
print("int:", [random.randint(1, 100) for _ in range(5)])
random.seed(42)
print("range:", [random.randrange(10) for _ in range(5)])
random.seed(42)
print("choice:", [random.choice([5, 6, 7, 8]) for _ in range(3)])
random.seed(42)
l = [1, 2, 3, 4]
random.shuffle(l)
print("shuffled:", l)
random.seed(42)
print("uniform:", round(random.uniform(1, 2), 15))
random.seed(42)
print("gauss:", [round(random.gauss(0, 1), 15) for _ in range(2)])
random.seed(42)
print("bits:", random.getrandbits(10), random.getrandbits(40))
random.seed(42)
print("sample:", random.sample(range(10), 3))
random.seed(42)
print("state0:", random.getstate()[1][0], random.getstate()[0])
random.setstate((3, random.getstate()[1], None))
print("setstate ok", random.random() > 0)
random.seed()
print("reseed ok")

random.seed(42)
print("stream:", [random.getrandbits(32) for _ in range(20)])
random.seed(42)
print("choice:", [random.choice([5, 6, 7, 8]) for _ in range(3)])
random.seed(42)
l = [1, 2, 3, 4]
random.shuffle(l)
print("shuffled:", l)
random.seed(42)
print("sample:", random.sample(range(10), 3))
random.seed(42)
print("bits:", random.getrandbits(10), random.getrandbits(40))
