# Fix: 嵌套容器的相等判定 (v0.5.0-alpha.3 起退化为身份比较的回归修复)

print([[1]] == [[1]])
print((1, 'a') == (1, 'a'))
print({1: (1, 2)} == {1: (1, 2)})
print(((1, 'a'),) == ((1, 'a'),))
print([1, 2] in [[1, 2]])
print((2, 'b') in [(1, 'a'), (2, 'b')])
print([[1], [2]].index([2]))
print([[1], [1]].count([1]))
print([1] in {1: [1]}.values())
print([[1], [2]].remove([2]) == None)
print([[1], [2], [1]].count([1]))
print([{1: 'a'}] == [{1: 'a'}])
print({'k': [1, [2]]} == {'k': [1, [2]]})
print((1, (2, (3,))) == (1, (2, (3,))))
print([None] == [None])
print([[1]] != [[1], [1]])
