# Feature: bytes() 构造与 bytes 方法族

b = b'hello'
print(b.decode())
print(b.hex())
print(b'ABC'.lower())
print(b'abc'.upper())
print(b'ab'.title())
print(b' x '.strip())
print(b'a,b,c'.split(b','))
print(b'aaa'.replace(b'a', b'b'))
print(b'hello'.find(b'll'))
print(b'hello'.index(b'l'))
print(b'hello'.count(b'l'))
print(b'abc'.startswith(b'ab'))
print(b'abc'.endswith(b'c'))
print(b'-'.join([b'a', b'b']))
print(bytes(3))
print(bytes([104, 105]))
print(bytes('hi', 'utf-8'))
print(bytes(b'hi'))
print('hi'.encode())
print(len(bytes(3)))
print('done')
