# .format() 嵌套格式规格 (alpha.5, P0-26)
w = 6
print("{:{w}}".format(5, w=6))
print("{0:{w}}".format(5, w=6))
print(f"[{1:{w}}]")
print("{value:{width}}".format(value=7, width=5))
print("{:{w}.{p}f}".format(3.14159, w=8, p=2))
print("{:{}}".format(5, 6))
print("{0:{1}}".format(5, 6))
print("|{:<{w}}|{:^{w}}|".format("a", "b", w=5))
