# Feature: 字面量转义序列解码 (str 与 bytes)

print(len('\x41'), '\x41')
print(len('\u4e2d'), '\u4e2d')
print(len('\101'), '\101')
print(len('\N{BULLET}'), '\N{BULLET}')
print(ord('\a'), ord('\b'), ord('\f'), ord('\v'))
print('\x412')
print('\U0001F600')
print('\8', '\p', len('\8'))
print('cont-ok')

print(len(b'\x41'), list(b'\x41'))
print(len(b'\x00'), list(b'\x00'))
print(list(b'\xff'), list(b'\400'))
print(b'\u4e2d', len(b'\u4e2d'))
print(b'\N{BULLET}', len(b'\N{BULLET}'))
print('\N{LATIN CAPITAL LETTER A}', '\N{SPACE}')
print(chr(92) + 'x41' == '\x41')
print(r'\x41' == chr(92) + 'x41')
print(len(r'\n'), len('\n'))
